services:
  redis:
      image: "redis:alpine"
      container_name: fraud-redis
      ports:
        - "6379:6379"

  trainer:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fraud-trainer
    command: >
      python3 -m training.train_v2
      --model logistic_regression
      --save
    environment:
      - ENVIRONMENT=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fraud-backend
    environment:
      - ENVIRONMENT=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
    - redis

  producer:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fraud-producer
    depends_on:
      - redis
    command: python -m api.producer
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fraud-consumer
    depends_on:
      - redis
      - trainer
    command: python -m api.consumer
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fraud-frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - BACKEND_HOST=api
      - API_PORT=8000
